### ISSUE TITLE
Expressionify doesn't work with IIncludableQuery<T> 

### ISSUE THREAD

**Issue by GoNextGroup** [ClaveConsulting/Expressionify#17]
Hello.

I've found the code like this won't work properly. 

`var wallet = await userDbContext.Wallets.Expressionify().Include(e => e.WalletTransactions.Where(f => f.Date.InRangeDateTime(payload.Dates))).FirstOrDefaultAsync(e => e.UserId == user.Id, cancellationToken: cancellationToken);`

Here `userDbContext` just a DbContext with `DbSet<User>`, `DbSet<Wallet>`,

```
public class User
{
      public Guid Id { get; set; }

      public Wallet Wallet { get; set; }
}

public class Wallet
{
      public Guid Id { get; set; }

      public ICollection<WalletTransaction> WalletTransactions { get; set; }

      public Guid UserId { get; set; }
}

public class WalletTransaction
{
      public Guid Id { get; set; }

      public DateTime Date  { get; set; }

      public Guid WalletId{ get; set; }
}
```

Here `InRangeDateTime` is a simple static method formed on rules for Expressionify successful usage.

```
public static partial class RangeInternalComprasion //ToDo: wait till Clave will allow to use generics
{
        [Expressionify]
        public static bool InRangeDateTime(this DateTime elem, RangeInternal<DateTime> toCompare) 
                => toCompare.From <= elem && toCompare.To >= elem;
}

public record RangeInternal<TType>
{
        public TType From { get; set; }
        public TType To { get; set; }
}
```

So, is this a global temporal or permanent limitation of Expressionify usage?

**Comment by mariusGundersen** [comment]
Try putting the `.Expressionify()` after the `.Include()`

**Comment by GoNextGroup** [comment]
Thank you so much! This works fine!
