### ISSUE TITLE
Question: AddCheckConstraint

### ISSUE THREAD

**Issue by molinch** [ClaveConsulting/Expressionify#27]
Thanks for Expressionify we use it extensively it's such a help, before we had duplicated logic and it was a pain to maintain :)

I assume that there are somewhere in the source code classes that deal with the translation of ExpressionTrees to partial SQL. Am I right?
If yes, could you point me into the direction so I can find a way to generate AddCheckConstraint logical constraint using ExpressionTrees?

**Comment by mariusGundersen** [comment]
It is EF that translate the expression into sql, just like it does for any other expression. The only thing this project does is tell EF that a method call should be converted into an expression, and then EF converts that expression into sql.

I'm not familiar with AddCheckConstraint, but it seems like something that applies to migrations? Do you have an example of how you use AddCheckConstraint today?

**Comment by molinch** [comment]
Yes, for example here, where builder is an instance of EntityTypeBuilder<T>:
```sql
builder.ToTable(b => b.HasCheckConstraint($"CK_AssignedTo_SuggestedAgent",
"""
    ([AssignedTo] IS NULL OR [SuggestedAgent] IS NULL)
"""));
```

Which would have been a super simple expression, if the functionality was there:
```csharp
a => a.AssignedTo == null || a.SuggestedAgent == null
```

**Comment by mariusGundersen** [comment]
The problem here is that `a` in the expression needs to be of the entity type, but the entity type only represents the latest version, while the migration is of a previous version. If you you later on remove the property `AssignedTo` then the code fails to compile, but it's needed for the migration.

**Comment by molinch** [comment]
Yes I guess it would at least require to define the check constraint name manually so it can keep track of it.
Anyway, we can close this. Thanks for helping out here, much appreciated :)
